DROP TABLE IF EXISTS customer_order;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS product;

-- Use IDENTITY em vez de AUTO_INCREMENT
CREATE TABLE customer (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100),
  email VARCHAR(100)
);

CREATE TABLE product (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description VARCHAR(100),
  price INTEGER
);

CREATE TABLE customer_order (
  order_id UUID DEFAULT random_uuid() PRIMARY KEY,
  customer_id INTEGER,
  product_id INTEGER,
  amount INTEGER,
  order_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_customer FOREIGN KEY (customer_id) REFERENCES customer(id) ON DELETE CASCADE,
  CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES product(id)
);

-- Inserts permanecem iguais
INSERT INTO customer(name, email)
VALUES
  ('sam', 'sam@gmail.com'),
  ('mike', 'mike@gmail.com'),
  ('jake', 'jake@gmail.com'),
  ('emily', 'emily@example.com'),
  ('sophia', 'sophia@example.com'),
  ('liam', 'liam@example.com'),
  ('olivia', 'olivia@example.com'),
  ('noah', 'noah@example.com'),
  ('ava', 'ava@example.com'),
  ('ethan', 'ethan@example.com');

INSERT INTO product(description, price)
VALUES
  ('iphone 20', 1000),
  ('iphone 18', 750),
  ('ipad', 800),
  ('mac pro', 3000),
  ('apple watch', 400),
  ('macbook air', 1200),
  ('airpods pro', 250),
  ('imac', 2000),
  ('apple tv', 200),
  ('homepod', 300);

INSERT INTO customer_order (customer_id, product_id, amount, order_date)
VALUES
  (1, 1, 950, CURRENT_TIMESTAMP),
  (1, 2, 850, CURRENT_TIMESTAMP),
  (2, 1, 975, CURRENT_TIMESTAMP),
  (2, 4, 2999, CURRENT_TIMESTAMP),
  (3, 2, 750, CURRENT_TIMESTAMP),
  (3, 2, 775, CURRENT_TIMESTAMP);